version: "2"
services:
  all-all-fake-connector:
    image: ernestio/all-all-fake-connector:1.8.0
    links:
    - nats
    - redis
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  api-gateway:
    image: ernestio/api-gateway:1.8.0
    ports:
    - 8080:8080
    links:
    - nats
    depends_on:
    - config-store
    environment:
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  aws-definition-mapper:
    image: ernestio/aws-definition-mapper:1.8.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  config-store:
    image: ernestio/config-store:1.8.0
    entrypoint: /go/bin/config-store -config /etc/ernest/config.json
    volumes:
    - ./config/config-store/:/etc/ernest/
    links:
    - nats
    environment:
      NATS_URI: nats://nats:4222
  datacenter-store:
    image: ernestio/datacenter-store:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  definition-mapper:
    image: ernestio/definition-mapper:1.8.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  elb-creator-aws-connector:
    image: ernestio/elb-creator-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  elb-deleter-aws-connector:
    image: ernestio/elb-deleter-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  elb-updater-aws-connector:
    image: ernestio/elb-updater-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  execution-adapter:
    image: ernestio/execution-adapter:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  execution-builder:
    image: ernestio/execution-builder:1.8.0
    links:
    - nats
    - redis
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  execution-run-salt-connector:
    image: ernestio/execution-run-salt-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  firewall-creator-aws-connector:
    image: ernestio/firewall-creator-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  firewall-creator-vcloud-connector:
    image: ernestio/firewall-creator-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  firewall-deleter-aws-connector:
    image: ernestio/firewall-deleter-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  firewall-updater-aws-connector:
    image: ernestio/firewall-updater-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  firewall-updater-vcloud-connector:
    image: ernestio/firewall-updater-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  generic-adapter:
    image: ernestio/generic-adapter:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  generic-builder:
    image: ernestio/generic-builder:1.8.0
    links:
    - nats
    - redis
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  group-store:
    image: ernestio/group-store:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  instance-creator-aws-connector:
    image: ernestio/instance-creator-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  instance-creator-vcloud-connector:
    image: ernestio/instance-creator-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  instance-deleter-aws-connector:
    image: ernestio/instance-deleter-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  instance-deleter-vcloud-connector:
    image: ernestio/instance-deleter-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  instance-updater-aws-connector:
    image: ernestio/instance-updater-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  instance-updater-vcloud-connector:
    image: ernestio/instance-updater-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  logger:
    image: ernestio/logger:1.8.0
    volumes:
    - ./logs/:/var/logs/
    links:
    - nats
    environment:
      ERNEST_LOG_FILE: /var/logs/ernest.log
      NATS_URI: nats://nats:4222
  monit:
    image: ernestio/monit:1.8.0
    ports:
    - 22000:22000
    links:
    - nats
    depends_on:
    - config-store
    environment:
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  nat-creator-aws-connector:
    image: ernestio/nat-creator-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  nat-creator-vcloud-connector:
    image: ernestio/nat-creator-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  nat-deleter-aws-connector:
    image: ernestio/nat-deleter-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  nat-updater-aws-connector:
    image: ernestio/nat-updater-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  nat-updater-vcloud-connector:
    image: ernestio/nat-updater-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  nats:
    image: nats
    ports:
    - 4222:4222
  network-creator-aws-connector:
    image: ernestio/network-creator-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  network-creator-vcloud-connector:
    image: ernestio/network-creator-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  network-deleter-aws-connector:
    image: ernestio/network-deleter-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  network-deleter-vcloud-connector:
    image: ernestio/network-deleter-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  nginx:
    image: nginx
    ports:
    - 443:443
    volumes:
    - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
    - ./config/nginx/ernest.key:/etc/nginx/conf.d/ernest.key
    - ./config/nginx/ernest.crt:/etc/nginx/conf.d/ernest.crt
    links:
    - api-gateway:api-gateway
    - monit:monit
  postgres:
    image: r3labs/postgres
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: users,groups,datacenters,services
  redis:
    image: redis
  route53-all-aws-connector:
    image: ernestio/route53-all-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  router-creator-vcloud-connector:
    image: ernestio/router-creator-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  router-deleter-vcloud-connector:
    image: ernestio/router-deleter-vcloud-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  s3-all-aws-connector:
    image: ernestio/s3-all-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  service-store:
    image: ernestio/service-store:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  user-store:
    image: ernestio/user-store:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  vcloud-definition-mapper:
    image: ernestio/vcloud-definition-mapper:1.8.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  vpc-creator-aws-connector:
    image: ernestio/vpc-creator-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  vpc-deleter-aws-connector:
    image: ernestio/vpc-deleter-aws-connector:1.8.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
  workflow-manager:
    image: ernestio/workflow-manager:1.8.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      NATS_URI: nats://nats:4222
networks: {}
